image: codewithpassion/www.openrov.com-build
stages:
   - deploy

before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y ) 
    - eval $(ssh-agent -s) 

deploy_prod:
  stage: deploy
  script:
    # add ssh key stored in DEPLOY_KEY variable to the agent store
    - ssh-add <(echo "$DEPLOY_KEY")
    - bower install --allow-root
    - npm install 
    - gulp deploy:prod --nodocker
  environment:
    name: PROD
    url: https://www.openrov.com
  only:
    - production
  tags: 
    - docker

deploy_staging:
  stage: deploy
  script:
    # add ssh key stored in DEPLOY_KEY variable to the agent store
    - ssh-add <(echo "$DEPLOY_KEY")
    - bower install --allow-root
    - npm install 
    - gulp deploy:staging
  environment:
    name: STAGING
    url: http://staging.openrov.com
  only:
    - master
  tags: 
    - docker
