image: node:8.1
before_script:
  - npm install -yg bower gulp docker

build:
  script:
    - npm install 
    - bower install --allow-root
    - gulp build
  only:
    - master
  tags:
    - docker    