---
title: OpenROV Underwater Drones
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
  values:
    image: "/images/openrov-trident-underwater-drone.jpg"
    height: 1200
    width: 1200
gems:
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-sitemap
exclude: 
array: []
webmaster_verifications:
  google: 6sqA5KNpZtZaQPB-78QcD8CDqXsbhOiqpZGvm NxYDI4
description: Trident is the latest high performing underwater drone from OpenROV,
  makers of powerful tools for marine exploration.
url: https://www.openrov.com
author:
  name: OpenROV
  email: info@openrov.com
  twitter: openrov
  facebook: OpenROV
  instagram: openrov_hq
twitter:
  username: openrov
social:
  name: OpenROV
  links:
  - https://twitter.com/OpenROV
  - https://www.facebook.com/OpenROV
  - https://www.instagram.com/openrov_hq
  - https://www.youtube.com/user/OpenROV
logo: "/images/openrov.png"
